# Show all possible defaults keys
defaults:
  data-source: beaker-ds
  query-interval: 1m
  query-timeout: 20s
  query-value-on-error: -1

# Defined data sources
data-sources:
  beaker-ds:
    driver: mysql
    properties:
      host: 192.168.120.104
      port: 3306
      user: admin
      password: admin
      database: beaker

