{
 "title": "Beaker in a Box",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Machine Architectures",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (arch) (query_result_arch_machines_available__avail)"
    },
    {
     "expr": "sum by (arch) (query_result_arch_machines_available__reserv)"
    },
    {
     "expr": "sum by (arch) (query_result_arch_machines_available__pend)"
    }
   ]
  },
  {
   "title": "Install Options",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": " (query_result_distros_per_arch)"
    }
   ]
  },
  { "title": "System Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Percent Machines Broken Per Arch",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum by (arch) (query_result_total_machines_broken_per_arch) / sum by(arch) (query_result_total_machines_per_arch)",
     "legendFormat": "{{arch}}"
    }
   ]
  },
  {
   "title": "Available Machines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "query_result_machines_available",
     "legendFormat": "available"
    },
    { "expr": "query_result_machines_total", "legendFormat": "total" },
    { "expr": "query_result_machines_reserved", "legendFormat": "reserved" },
    { "expr": "query_result_machines_broken", "legendFormat": "broken" }
   ]
  },
  {
   "title": "Average Queue Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "query_result_arch_avg_queue_time",
     "legendFormat": "{{arch}}"
    }
   ]
  },
  { "title": "Recipe Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Current Recipe's Status",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "query_result_recipes_running_status",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(query_result_recipes_running_status)",
     "legendFormat": "Total Unfinished Recipes"
    }
   ]
  },
  {
   "title": "Recipes Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 43 },
   "targets": [
    {
     "expr": "query_result_recipes_running_status",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Recipes per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by (arch) (query_result_arch_recipes_per_day)",
     "legendFormat": "{{arch}}"
    },
    {
     "expr": "avg(sum by(fqdn) (query_result_machine_recipes_per_day))",
     "legendFormat": "Total average"
    }
   ]
  },
  { "title": "User Group Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "query_result_users_total", "legendFormat": "Total Users" }
   ]
  },
  {
   "title": "Total Group Hours per Arch",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 11, "x": 5, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (group_name, arch) (query_result_hours_arch_per_group))",
     "legendFormat": "{{group_name}} on {{arch}}"
    }
   ]
  },
  {
   "title": "User Groups",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "query_result_users_per_group", "legendFormat": "{{display_name}}" }
   ]
  }
 ]
}